name: Build asterisk

on:
  workflow_dispatch:

  push:
    paths:
      - .github/workflows/build-asterisk.yml
      - 'asterisk-releases.txt'

jobs:
  build-asterisk:
    timeout-minutes: 600
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        releases: ['1.2', '1.4', '1.6', '1.8', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']
      fail-fast: false

    steps:
      - run: |
          set -x
          echo "Processing asterisk releases for v. ${{ matrix.releases }}.x"
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}


